apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: redis-ha
spec:
  ports:
  - port: 6379
    name: server
  - port: 26379
    name: sentinel
  clusterIP: None
  selector:
    app: redis-ha
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rds
spec:
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-ha

    spec:
      containers:
        - name: server
          image: reallyenglish/k8s-redis-ha-server:3.2.8
          env:
          - name: SRV_NAME
            value: redis-ha
          - name: REDIS_DATA_DIR
            value: /data
          - name: REDIS_BIND_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /etc/redis
              name: redis-config

        - name: sentinel
          image: reallyenglish/k8s-redis-ha-sentinel:3.2.8
          env:
          - name: SRV_NAME
            value: redis-ha
          - name: REDIS_MASTER_NAME
            value: ha-master
          - name: SENTINEL_QUORUM
            value: "2"
          - name: SENTINEL_BIND_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: sentinel
              containerPort: 26379
              protocol: "TCP"
          volumeMounts:
            - mountPath: /etc/redis
              name: sentinel-config

      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          items:
            - key: redis-dot-conf
              path: server.conf.template
      - name: sentinel-config
        configMap:
          name: sentinel-config
          items:
            - key: sentinel-dot-conf
              path: sentinel.conf.template

  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
